# Generated by Django 5.0.4 on 2024-04-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='caseIdentifier',
            field=models.CharField(default='NEW_CASE_FILE', max_length=300),
            preserve_default=False,
        ),
    ]
