# Generated by Django 5.0.4 on 2024-04-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseManagement', '0002_casefile_caseidentifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefile',
            name='tags',
            field=models.CharField(default='[{"Key": null, "Value": null}]', max_length=300),
        ),
    ]
