# Generated by Django 5.0.4 on 2024-04-21 00:11

import CaseManagement.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseManagement', '0003_casefile_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300, unique=True)),
                ('value', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='casefile',
            name='tags',
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='additionalIdentifications',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='additionalNames',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='associatedAddresses',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='currentAddress',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='dateOfBirth',
            field=models.DateTimeField(blank=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='driversLicenseNumber',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='governmentIssueId',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='lastName',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='middleNames',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='previousAddresses',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='socialSecurityNumber',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='targetJustification',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='casefile',
            name='tagSet',
            field=models.ForeignKey(default=CaseManagement.models.Tag.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='CaseManagement.tag'),
        ),
    ]
