# Generated by Django 5.0.4 on 2024-04-21 16:57

import CaseManagement.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseManagement', '0006_alter_casefile_tagset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casefile',
            name='tagSet',
        ),
        migrations.AddField(
            model_name='tag',
            name='casefile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CaseManagement.casefile'),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='caseIdentifier',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='createdBy',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='dateCreated',
            field=models.DateTimeField(blank=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='dateLastModified',
            field=models.DateTimeField(blank=True, verbose_name='date last modified'),
        ),
        migrations.AlterField(
            model_name='casefile',
            name='lastModifiedBy',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
