# Generated by Django 5.0.4 on 2024-06-24 01:25

import CaseManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseManagement', '0007_remove_casefile_tagset_tag_casefile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='casefile',
            field=models.ForeignKey(default=None, on_delete=models.SET(None), to='CaseManagement.casefile'),
        ),
    ]
