# Generated by Django 5.0.4 on 2024-07-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseManagement', '0011_alter_casefile_datecreated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVE', 'Archive'), ('LONGTERM MONITOR', 'Longterm Monitor'), ('DECEASED', 'Deceased'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
    ]
