# Generated by Django 5.0.4 on 2024-07-12 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseManagement', '0013_alter_casefile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casefile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CaseManagement.casefile')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300)),
                ('value', models.CharField(max_length=300)),
                ('tagSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CaseManagement.tagset')),
            ],
        ),
    ]
