# Generated by Django 5.0.4 on 2024-07-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseManagement', '0015_alter_tagset_casefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetofinterest',
            name='additionalIdentifications',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='additionalNames',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='associatedAddresses',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='currentAddress',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='dateOfBirth',
            field=models.DateTimeField(default='', verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='driversLicenseNumber',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='governmentIssueId',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='lastName',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='middleNames',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='previousAddresses',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='socialSecurityNumber',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='targetofinterest',
            name='targetJustification',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
