# Generated by Django 5.0.4 on 2024-07-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CaseManagement', '0016_alter_targetofinterest_additionalidentifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetofinterest',
            name='dateOfBirth',
            field=models.DateTimeField(default='536-08-26T15:13:46Z', verbose_name='Date of Birth'),
        ),
    ]
