name: Production environment workflow

run-name: ${{ github.actor }} has pushed obsidia to the production environment

on:
  push:
    branches:
      - "production"

env:
  LATEST_TEST: cypher4859/obsidia-api:latest-test
  LATEST_PRODUCTION: cypher4859/obsidia-api:latest-production

jobs:
  build-push-production-image:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 
        run: |
          docker image pull ${{ env.LATEST_TEST }}
          docker image tag ${{ env.LATEST_TEST }} ${{ env.LATEST_PRODUCTION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.LATEST_PRODUCTION }}
