name: Test environment workflow

run-name: ${{ github.actor }} has pushed obsidia to the test environment

on:
  push:
    branches:
      - "test"

env:
  LATEST_TEST: cypher4859/obsidia-api:latest-test
  LATEST_DEVELOP: cypher4859/obsidia-api:latest-develop

jobs:
  build-push-test-image:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Tests
        if: ${{ hashFiles('./tests/') != '' }}
        run: |
          docker image tag ${{ env.LATEST_DEVELOP }} ${{ env.LATEST_TEST }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.LATEST_DEVELOP }}
