name: pull request workflow

run-name: ${{ github.actor }} has opened a PR for branch ${{ github.head_ref }}; we're testing it

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  PR_IMAGE_TAG: cypher4859/obsidia-api:pr

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Tests
        if: ${{ hashFiles('./tests/') != '' }}
        run: |
          docker build --pull --target test -t ${{ env.TEST_TAG }} .

  # build-push-image-branch:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - run-tests

  #   steps:
  #     - name: (Dependency) Checkout
  #       uses: actions/checkout@v4

  #     - name: (Dependency) Set up QEMU
  #       uses: docker/setup-qemu-action@v3
      
  #     - name: (Dependency) Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
      
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
      
  #     - name: Build and push to obsidia-api:pr-${{ github.head_ref }}
  #       uses: docker/build-push-action@v5
  #       with:
  #         push: true
  #         tags: "${{ env.PR_IMAGE_TAG }}-${{ github.head_ref }}"